//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Image
    {
        public int ImageId { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }

        [DisplayName("Upload File")]

        public string ImagePath { get; set; }

        [Required(ErrorMessage = "Image file is required.")]

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
